version: "5.15.8"

services:
  omada-controller:
    container_name: omada-controller
    image: omada-controller:latest
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    network_mode: host
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs

volumes:
  omada-data: /var/lib/omanda/data
  omada-logs: /var/log/omanda/logs
